// 50 PROGRAMMING QUESTIONS DATABASE
const QUESTION_DATABASE = [
    // ==================== HTML (10 Questions) ====================
    { id: 1, difficulty: "easy", question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Markup Language", "Home Tool Markup Language"], correct: 0, points: 10, category: "HTML", explanation: "HTML stands for Hyper Text Markup Language - the standard markup language for creating web pages." },
    { id: 2, difficulty: "easy", question: "Which tag is used to create a hyperlink?", options: ["<a>", "<link>", "<href>", "<url>"], correct: 0, points: 10, category: "HTML", explanation: "The <a> tag (anchor tag) is used to create hyperlinks." },
    { id: 3, difficulty: "easy", question: "What is the correct HTML for creating a paragraph?", options: ["<p>", "<para>", "<paragraph>", "<pg>"], correct: 0, points: 10, category: "HTML", explanation: "<p> is the HTML tag for paragraphs." },
    { id: 4, difficulty: "easy", question: "Which tag is used to display an image?", options: ["<img>", "Image", "<pic>", "<src>"], correct: 0, points: 10, category: "HTML", explanation: "The <img> tag is used to embed images." },
    { id: 5, difficulty: "easy", question: "What is the largest heading tag?", options: ["<h1>", "<h6>", "<heading>", "<head>"], correct: 0, points: 10, category: "HTML", explanation: "<h1> is the largest heading, <h6> is the smallest." },
    { id: 6, difficulty: "easy", question: "What does <ul> create?", options: ["Unordered list", "Ordered list", "Underline", "Upper list"], correct: 0, points: 10, category: "HTML", explanation: "<ul> creates an unordered (bulleted) list." },
    { id: 7, difficulty: "easy", question: "What does <ol> create?", options: ["Ordered list", "Unordered list", "Outline", "Orange list"], correct: 0, points: 10, category: "HTML", explanation: "<ol> creates an ordered (numbered) list." },
    { id: 8, difficulty: "easy", question: "Which tag defines a table row?", options: ["<tr>", "<td>", "<th>", "<table>"], correct: 0, points: 10, category: "HTML", explanation: "<tr> defines a table row, <td> defines table data." },
    { id: 9, difficulty: "easy", question: "What is the correct HTML for a text input?", options: ["<input type='text'>", "<textfield>", "<input>", "<text>"], correct: 0, points: 10, category: "HTML", explanation: "<input type='text'> creates a text input field." },
    { id: 10, difficulty: "easy", question: "Which tag creates a line break?", options: ["<br>", "<lb>", "<break>", "<newline>"], correct: 0, points: 10, category: "HTML", explanation: "<br> creates a line break." },
    
    // ==================== CSS (10 Questions) ====================
    { id: 11, difficulty: "easy", question: "What does CSS stand for?", options: ["Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], correct: 0, points: 10, category: "CSS", explanation: "CSS stands for Cascading Style Sheets." },
    { id: 12, difficulty: "easy", question: "How do you select an element with class 'box'?", options: [".box", "#box", "*box", "box"], correct: 0, points: 10, category: "CSS", explanation: ".box selects all elements with class='box'." },
    { id: 13, difficulty: "easy", question: "How do you select an element with id 'header'?", options: ["#header", ".header", "*header", "header"], correct: 0, points: 10, category: "CSS", explanation: "#header selects the element with id='header'." },
    { id: 14, difficulty: "easy", question: "What property changes text color?", options: ["color", "text-color", "font-color", "text"], correct: 0, points: 10, category: "CSS", explanation: "color property changes text color." },
    { id: 15, difficulty: "easy", question: "What property changes background color?", options: ["background-color", "bgcolor", "color-background", "background"], correct: 0, points: 10, category: "CSS", explanation: "background-color sets background color." },
    { id: 16, difficulty: "easy", question: "What property changes font size?", options: ["font-size", "text-size", "size", "font"], correct: 0, points: 10, category: "CSS", explanation: "font-size controls text size." },
    { id: 17, difficulty: "easy", question: "How do you add a border?", options: ["border: 1px solid black", "border: black", "border-size: 1px", "border-color: black"], correct: 0, points: 10, category: "CSS", explanation: "border: width style color adds border." },
    { id: 18, difficulty: "easy", question: "What property controls spacing inside element?", options: ["padding", "margin", "spacing", "inner-space"], correct: 0, points: 10, category: "CSS", explanation: "padding creates space inside element." },
    { id: 19, difficulty: "easy", question: "What property controls spacing outside element?", options: ["margin", "padding", "spacing", "outer-space"], correct: 0, points: 10, category: "CSS", explanation: "margin creates space outside element." },
    { id: 20, difficulty: "easy", question: "How do you center text?", options: ["text-align: center", "align: center", "text-center", "center-text"], correct: 0, points: 10, category: "CSS", explanation: "text-align: center centers text." },
    
    // ==================== JavaScript (15 Questions) ====================
    { id: 21, difficulty: "easy", question: "How do you write an IF statement in JavaScript?", options: ["if (i == 5)", "if i == 5 then", "if i = 5", "if i == 5 then"], correct: 0, points: 10, category: "JavaScript", explanation: "if (condition) is correct syntax." },
    { id: 22, difficulty: "easy", question: "Which symbol is used for single-line comments?", options: ["//", "<!-- -->", "/* */", "#"], correct: 0, points: 10, category: "JavaScript", explanation: "// is for single-line comments." },
    { id: 23, difficulty: "easy", question: "What does 'console.log()' do?", options: ["Prints to browser console", "Creates alert", "Writes to file", "Logs user out"], correct: 0, points: 10, category: "JavaScript", explanation: "console.log() outputs to browser console." },
    { id: 24, difficulty: "easy", question: "How do you declare a variable?", options: ["var x", "variable x", "x = var", "declare x"], correct: 0, points: 10, category: "JavaScript", explanation: "var, let, const declare variables." },
    { id: 25, difficulty: "easy", question: "What is '5' + 3 in JavaScript?", options: ["53", "8", "Error", "undefined"], correct: 0, points: 10, category: "JavaScript", explanation: "String concatenation: '5' + 3 = '53'." },
    { id: 26, difficulty: "easy", question: "How do you create a function?", options: ["function myFunction()", "def myFunction()", "func myFunction()", "create myFunction()"], correct: 0, points: 10, category: "JavaScript", explanation: "function name() { } declares a function." },
    { id: 27, difficulty: "easy", question: "What is an array?", options: ["Collection of elements", "Single variable", "Function", "Loop"], correct: 0, points: 10, category: "JavaScript", explanation: "Arrays store multiple values." },
    { id: 28, difficulty: "easy", question: "What does 'typeof' operator do?", options: ["Returns data type", "Checks type", "Converts type", "Compares type"], correct: 0, points: 10, category: "JavaScript", explanation: "typeof returns variable type as string." },
    { id: 29, difficulty: "easy", question: "What is '===' operator?", options: ["Strict equality", "Value equality", "Assignment", "Comparison"], correct: 0, points: 10, category: "JavaScript", explanation: "=== compares both value and type." },
    { id: 30, difficulty: "easy", question: "What is the difference between '==' and '==='?", options: ["== compares value, === compares value and type", "Same thing", "=== compares value only", "== compares type only"], correct: 0, points: 10, category: "JavaScript", explanation: "== does type coercion, === does strict equality." },
    { id: 31, difficulty: "medium", question: "What is a closure in JavaScript?", options: ["Function with access to outer scope", "Closing window", "Type of loop", "CSS property"], correct: 0, points: 20, category: "JavaScript", explanation: "Closure has access to outer function's variables." },
    { id: 32, difficulty: "medium", question: "What is 'this' keyword?", options: ["Refers to current object", "Creates object", "Defines function", "Declares variable"], correct: 0, points: 20, category: "JavaScript", explanation: "'this' refers to the object executing current function." },
    { id: 33, difficulty: "medium", question: "What is the difference between 'let' and 'var'?", options: ["let is block-scoped, var is function-scoped", "Same thing", "var is block-scoped", "let is global"], correct: 0, points: 20, category: "JavaScript", explanation: "let is block-scoped, var is function-scoped." },
    { id: 34, difficulty: "medium", question: "What is a Promise?", options: ["Async operation object", "Function", "Loop", "Variable"], correct: 0, points: 20, category: "JavaScript", explanation: "Promise represents eventual completion of async operation." },
    { id: 35, difficulty: "medium", question: "What does 'map()' do?", options: ["Creates new array", "Filters array", "Reduces array", "Finds element"], correct: 0, points: 20, category: "JavaScript", explanation: "map() creates new array by applying function to each element." },
    
    // ==================== Python (10 Questions) ====================
    { id: 36, difficulty: "easy", question: "How do you print in Python?", options: ["print()", "console.log()", "echo()", "printf()"], correct: 0, points: 10, category: "Python", explanation: "print() outputs to console." },
    { id: 37, difficulty: "easy", question: "How do you comment in Python?", options: ["#", "//", "<!-- -->", "/* */"], correct: 0, points: 10, category: "Python", explanation: "# is for single-line comments." },
    { id: 38, difficulty: "easy", question: "How do you create a list?", options: ["[1,2,3]", "(1,2,3)", "{1,2,3}", "<1,2,3>"], correct: 0, points: 10, category: "Python", explanation: "Square brackets create lists." },
    { id: 39, difficulty: "easy", question: "How do you create a tuple?", options: ["(1,2,3)", "[1,2,3]", "{1,2,3}", "<1,2,3>"], correct: 0, points: 10, category: "Python", explanation: "Parentheses create tuples (immutable)." },
    { id: 40, difficulty: "easy", question: "How do you create a dictionary?", options: ["{'key':'value'}", "['key':'value']", "('key':'value')", "<'key':'value'>"], correct: 0, points: 10, category: "Python", explanation: "Curly braces with key:value pairs create dictionaries." },
    { id: 41, difficulty: "easy", question: "What is the correct if statement in Python?", options: ["if x == 5:", "if (x == 5)", "if x == 5 then", "if x = 5"], correct: 0, points: 10, category: "Python", explanation: "if condition: with colon is correct." },
    { id: 42, difficulty: "easy", question: "How do you define a function in Python?", options: ["def myFunction():", "function myFunction():", "func myFunction():", "define myFunction():"], correct: 0, points: 10, category: "Python", explanation: "def keyword defines functions." },
    { id: 43, difficulty: "medium", question: "What is list comprehension?", options: ["Concise way to create lists", "Loop comprehension", "Dictionary method", "String method"], correct: 0, points: 20, category: "Python", explanation: "List comprehension creates lists concisely: [x*2 for x in range(5)]" },
    { id: 44, difficulty: "medium", question: "What is the difference between list and tuple?", options: ["Mutable vs immutable", "Both mutable", "Both immutable", "List is faster"], correct: 0, points: 20, category: "Python", explanation: "Lists are mutable, tuples are immutable." },
    { id: 45, difficulty: "medium", question: "What does 'yield' do in Python?", options: ["Creates generator", "Returns value", "Stops function", "Raises error"], correct: 0, points: 20, category: "Python", explanation: "yield creates generator functions." },
    
    // ==================== Programming Concepts (5 Questions) ====================
    { id: 46, difficulty: "easy", question: "What is a variable?", options: ["Container for storing data", "Type of function", "Loop structure", "Conditional statement"], correct: 0, points: 10, category: "Concepts", explanation: "A variable stores data that can be changed." },
    { id: 47, difficulty: "easy", question: "What is a loop used for?", options: ["Repeat code multiple times", "Stop code execution", "Check conditions", "Store data"], correct: 0, points: 10, category: "Concepts", explanation: "Loops execute code repeatedly until condition is met." },
    { id: 48, difficulty: "medium", question: "What is an algorithm?", options: ["Step-by-step procedure", "Programming language", "Data structure", "Variable type"], correct: 0, points: 20, category: "Concepts", explanation: "An algorithm is a set of instructions to solve a problem." },
    { id: 49, difficulty: "medium", question: "What is the difference between compiler and interpreter?", options: ["Compiler translates whole program, interpreter line by line", "Same thing", "Interpreter translates whole", "Compiler runs line by line"], correct: 0, points: 20, category: "Concepts", explanation: "Compiler translates entire program at once, interpreter line by line." },
    { id: 50, difficulty: "medium", question: "What is recursion?", options: ["Function that calls itself", "Loop structure", "Data type", "Error handling"], correct: 0, points: 20, category: "Concepts", explanation: "Recursion is when a function calls itself to solve a problem." }
];